package pipeline

import (
	"context"
	"fmt"
	"io"
	"time"
)

// Outgoing is a fully-marshalled message ready for a sink: the raw Payload
// bytes plus the Key bytes (when the run configured a key) to associate with
// them. Sinks decode or forward these bytes as their transport requires.
type Outgoing struct {
	Key     []byte
	Payload []byte
}

// Sink is the destination seam for generated bytes. Adapters write to stdout
// (Dry run) or produce to Kafka. The Pipeline never knows which.
type Sink interface {
	Send(ctx context.Context, o Outgoing) error
	Close() error
}

// ValueGenerator is the seam between the Pipeline and payload generation. The
// generator produces a random value honouring the given JSON Schema, or a typed
// error when it cannot (ADR-0006). The Pipeline depends only on this interface;
// *generator.Generator satisfies it, and tests substitute a fake so pipeline
// tests never load a schema or touch an RNG.
type ValueGenerator interface {
	// Value generates a value conforming to schema, or an error when the schema
	// contains a construct that cannot be honoured.
	Value(schema map[string]any) (any, error)
}

// Config carries the fixed inputs of a run.
type Config struct {
	Generator ValueGenerator
	Schema    map[string]any
	Count     int
	RateLimit time.Duration
	KeyField  string
	// KeyBinding is the resolved message.bindings.kafka.key schema, or nil when
	// the spec declares no key binding. When non-nil and KeyField is empty, the
	// Key is generated from this schema instead of being extracted from the
	// Payload.
	KeyBinding map[string]any
	Encoder    Encoder
	// Warn, when non-nil, receives per-message stream diagnostics such as a
	// configured Key field that is missing from a generated Payload. Process
	// edge (main) passes stderr; tests pass a buffer.
	Warn io.Writer
}

// Stats reports the outcome of a run.
type Stats struct {
	Total   int64
	Acked   int64
	Failed  int64
	Elapsed time.Duration
}

// Pipeline drives a run: generate each Payload from the Message schema, extract
// the Key, encode via the injected Encoder, and hand bytes to the configured
// Sink until Count is reached or the context is cancelled.
type Pipeline struct {
	cfg  Config
	sink Sink
}

// New returns a Pipeline that sends generated payloads to the given sink.
func New(cfg Config, sink Sink) *Pipeline {
	return &Pipeline{cfg: cfg, sink: sink}
}

// Run executes the pipeline until Count payloads are handled, ctx is done, or
// generation of a Payload fails (ADR-0006): a schema the generator cannot
// honour errors every Payload the same way, so the run stops and the error is
// returned rather than being counted and looped past.
func (p *Pipeline) Run(ctx context.Context) (Stats, error) {
	var total, acked, failed int64
	start := time.Now()

	hasBinding := p.cfg.KeyBinding != nil
	hasKeyField := p.cfg.KeyField != ""

	if !hasBinding && !hasKeyField {
		p.warnf("no key configured, producing with a null key\n")
	}
	if hasBinding && hasKeyField {
		p.warnf("Warning: -key overrides binding, binding overridden\n")
	}

loop:
	for {
		if p.cfg.Count > 0 && total >= int64(p.cfg.Count) {
			break
		}

		select {
		case <-ctx.Done():
			break loop
		default:
		}

		var key any
		var err error
		if hasBinding && !hasKeyField {
			// Binding present, no -key: generate key from binding schema first so
			// an unhonorable binding aborts the run before any payload is counted.
			key, err = p.cfg.Generator.Value(p.cfg.KeyBinding)
			if err != nil {
				return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, err
			}
		}

		payload, err := p.cfg.Generator.Value(p.cfg.Schema)
		if err != nil {
			return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, err
		}
		total++

		if hasKeyField {
			// Binding absent or overridden: extract from payload.
			key = extractKey(payload, p.cfg.KeyField)
			if key == nil {
				p.warnf("Warning: field %q not found in payload, skipping\n", p.cfg.KeyField)
				failed++
				continue
			}
		}

		keyBytes, data, err := p.cfg.Encoder.Encode(key, payload)
		if err != nil {
			failed++
			continue
		}

		if err := p.sink.Send(ctx, Outgoing{Key: keyBytes, Payload: data}); err != nil {
			failed++
			continue
		}

		acked++
		// Rate limiting stays an inline sleep. A sleeper seam is deliberately
		// deferred until a second consumer of pacing exists (ADR-0004); revisit
		// only when pacing tests demand it.
		time.Sleep(p.cfg.RateLimit)
	}

	return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, nil
}

// extractKey pulls the value of keyField from the generated payload. keyField is
// a dotted JSON path (object traversals and array indexing, e.g. customer.id or
// items[0].sku); a plain top-level name works unchanged. Returns nil when the
// path is empty, an intermediate segment is missing, or an index is out of
// range, so the caller can count a failure and skip.
func extractKey(payload any, keyField string) any {
	segments, ok := parseKeyPath(keyField)
	if !ok {
		return nil
	}
	return resolveKeyPath(payload, segments)
}

// keySegment is one step of a JSON key path: a field name, or an array index.
type keySegment struct {
	// field is the object field name; used when index is -1.
	field string
	// index is the array index; -1 means this step is a field access.
	index int
}

// parseKeyPath splits a dotted JSON path (with optional [n] array indexing)
// into segments. Returns ok=false on an empty path or a malformed fragment
// (e.g. an unbalanced bracket).
func parseKeyPath(path string) ([]keySegment, bool) {
	if path == "" {
		return nil, false
	}
	var (
		segments []keySegment
		buf      []byte
	)
	flushField := func() {
		if len(buf) > 0 {
			segments = append(segments, keySegment{field: string(buf), index: -1})
			buf = buf[:0]
		}
	}
	var i int
	for i < len(path) {
		switch c := path[i]; c {
		case '.':
			flushField()
			i++
		case '[':
			flushField()
			close := i + 1
			for close < len(path) && path[close] != ']' {
				close++
			}
			if close >= len(path) {
				return nil, false
			}
			idxStr := path[i+1 : close]
			if idxStr == "" {
				return nil, false
			}
			n := 0
			for _, d := range idxStr {
				if d < '0' || d > '9' {
					return nil, false
				}
				n = n*10 + int(d-'0')
			}
			segments = append(segments, keySegment{index: n})
			i = close + 1
		default:
			buf = append(buf, c)
			i++
		}
	}
	flushField()
	return segments, true
}

// resolveKeyPath walks the segments through the payload, returning the value at
// the end of the path or nil when any step fails.
func resolveKeyPath(current any, segments []keySegment) any {
	for _, seg := range segments {
		if seg.index >= 0 {
			arr, ok := current.([]any)
			if !ok || seg.index >= len(arr) {
				return nil
			}
			current = arr[seg.index]
			continue
		}
		m, ok := current.(map[string]any)
		if !ok {
			return nil
		}
		v, ok := m[seg.field]
		if !ok {
			return nil
		}
		current = v
	}
	return current
}

func (p *Pipeline) warnf(format string, args ...any) {
	if p.cfg.Warn != nil {
		fmt.Fprintf(p.cfg.Warn, format, args...)
	}
}
