package pipeline

import (
	"context"
	"fmt"
	"io"
	"time"
)

// Outgoing is a fully-marshalled message ready for a sink: the raw Payload
// bytes plus the Key bytes (when the run configured a key) and the Headers
// (when its Message type declares them) to associate with them. Sinks decode
// or forward these bytes as their transport requires.
type Outgoing struct {
	Key     []byte
	Headers []Header
	Payload []byte
}

// Header is one Kafka record header: a name and a value, which is nil for a
// null header. A message's Headers come in a stable order (#85).
type Header struct {
	Name  string
	Value []byte
}

// Sink is the destination seam for generated bytes. Adapters write to stdout
// (Dry run) or produce to Kafka. The Pipeline never knows which.
type Sink interface {
	Send(ctx context.Context, o Outgoing) error
	Close() error
}

// PayloadGenerator is the seam between the Pipeline and message generation.
// The Wire format binds the schemas that govern it, so each Generate is a
// random message honouring the schema of the Message type it picked - its
// Payload, Headers and Key, every Planting already in place - or a typed error
// when the schema holds a construct that cannot be honoured (ADR-0006). The
// Pipeline knows no schema of any language, nor where a Key is planted; tests
// substitute a fake so they never load one or touch an RNG.
type PayloadGenerator interface {
	Generate() (Generated, error)
}

// Generated is one generated message and the Message type it is of: an index
// into the one slice of bound Message types the Wire format built for the run
// (wire.Bound, #109), which its generator and its Encoder share. The Pipeline
// carries it from the PayloadGenerator to the Encoder, so a Wire format that
// encodes each Message type differently knows which one a record is (#91).
// With one Message type it is always 0.
type Generated struct {
	Type int
	// Key is the message's Key, from the key schema; nil when the run has
	// none, and the record carries a null Key.
	Key     any
	Payload any
	// Headers are the record's Headers, generated from its Message type's
	// headers schema and already encoded, since every Wire format encodes
	// them alike (#85 decision 2); nil when it declares none.
	Headers []Header
}

// Config carries the fixed inputs of a run.
type Config struct {
	Generator PayloadGenerator
	Count     int
	RateLimit time.Duration
	// Keyed says the run's messages carry a Key from a key schema; without
	// one every record carries a null Key, which the Pipeline announces once.
	Keyed   bool
	Encoder Encoder
	// Warn, when non-nil, receives per-message stream diagnostics such as a
	// configured Key field that is missing from a generated Payload. Process
	// edge (main) passes stderr; tests pass a buffer.
	Warn io.Writer
}

// Stats reports the outcome of a run.
type Stats struct {
	Total   int64
	Acked   int64
	Failed  int64
	Elapsed time.Duration
}

// Pipeline drives a run: generate each message, encode it via the injected
// Encoder, and hand bytes to the configured Sink
// until Count is reached or the context is cancelled.
type Pipeline struct {
	cfg  Config
	sink Sink
}

// New returns a Pipeline that sends generated payloads to the given sink.
func New(cfg Config, sink Sink) *Pipeline {
	return &Pipeline{cfg: cfg, sink: sink}
}

// Run executes the pipeline until Count payloads are handled, ctx is done, or
// generation of a Payload fails (ADR-0006): a schema the generator cannot
// honour errors every Payload the same way, so the run stops and the error is
// returned rather than being counted and looped past.
func (p *Pipeline) Run(ctx context.Context) (Stats, error) {
	var total, acked, failed int64
	start := time.Now()

	if !p.cfg.Keyed {
		p.warnf("no key configured, generating messages with a null key\n")
	}

loop:
	for {
		if p.cfg.Count > 0 && total >= int64(p.cfg.Count) {
			break
		}

		select {
		case <-ctx.Done():
			break loop
		default:
		}

		generated, err := p.cfg.Generator.Generate()
		if err != nil {
			return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, err
		}
		total++

		keyBytes, data, err := p.cfg.Encoder.Encode(generated)
		if err != nil {
			failed++
			continue
		}

		if err := p.sink.Send(ctx, Outgoing{Key: keyBytes, Headers: generated.Headers, Payload: data}); err != nil {
			failed++
			continue
		}

		acked++
		// Rate limiting stays an inline sleep. A sleeper seam is deliberately
		// deferred until a second consumer of pacing exists (ADR-0004); revisit
		// only when pacing tests demand it.
		time.Sleep(p.cfg.RateLimit)
	}

	return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, nil
}

func (p *Pipeline) warnf(format string, args ...any) {
	if p.cfg.Warn != nil {
		fmt.Fprintf(p.cfg.Warn, format, args...)
	}
}
