package pipeline

import (
	"context"
	"fmt"
	"io"
	"time"
)

// Outgoing is a fully-marshalled message ready for a sink: the raw Payload
// bytes plus the Key bytes (when the run configured a key) to associate with
// them. Sinks decode or forward these bytes as their transport requires.
type Outgoing struct {
	Key     []byte
	Payload []byte
}

// Sink is the destination seam for generated bytes. Adapters write to stdout
// (Dry run) or produce to Kafka. The Pipeline never knows which.
type Sink interface {
	Send(ctx context.Context, o Outgoing) error
	Close() error
}

// PayloadGenerator is the seam between the Pipeline and payload generation. The
// Wire format binds the schemas that govern it, so each Generate is a random
// Payload honouring the schema of the Message type it picked, or a typed error
// when the schema holds a construct that cannot be honoured (ADR-0006). The
// Pipeline knows no schema of any language; tests substitute a fake so they
// never load one or touch an RNG.
type PayloadGenerator interface {
	Generate() (Generated, error)
}

// Generated is one generated Payload and the Message type it is of: an index
// into the Kafka topic's Message types, in the order the Wire format holds
// them. The Pipeline carries it from the PayloadGenerator to the Encoder, so
// a Wire format that encodes each Message type differently knows which one a
// record is (#91). With one Message type it is always 0.
type Generated struct {
	Type    int
	Payload any
}

// KeyPlan is the seam between the Pipeline and the Key of a run: it generates
// the Key from the key schema and, when -keyPath is set, plants it into the
// Payload, returning the value both then hold (ADR-0009). A nil KeyPlan means
// the run produces records with a null Key. *keyplan.Plan satisfies it, and
// tests substitute a fake, so the Pipeline knows neither schema language nor
// path syntax.
type KeyPlan interface {
	Apply(payload any) (any, error)
}

// Config carries the fixed inputs of a run.
type Config struct {
	Generator PayloadGenerator
	Count     int
	RateLimit time.Duration
	// KeyPlan, when set, produces the Key of each record; nil means a null Key.
	KeyPlan KeyPlan
	Encoder Encoder
	// Warn, when non-nil, receives per-message stream diagnostics such as a
	// configured Key field that is missing from a generated Payload. Process
	// edge (main) passes stderr; tests pass a buffer.
	Warn io.Writer
}

// Stats reports the outcome of a run.
type Stats struct {
	Total   int64
	Acked   int64
	Failed  int64
	Elapsed time.Duration
}

// Pipeline drives a run: generate each Payload, take its Key from the Key
// plan, encode via the injected Encoder, and hand bytes to the configured Sink
// until Count is reached or the context is cancelled.
type Pipeline struct {
	cfg  Config
	sink Sink
}

// New returns a Pipeline that sends generated payloads to the given sink.
func New(cfg Config, sink Sink) *Pipeline {
	return &Pipeline{cfg: cfg, sink: sink}
}

// Run executes the pipeline until Count payloads are handled, ctx is done, or
// generation of a Payload fails (ADR-0006): a schema the generator cannot
// honour errors every Payload the same way, so the run stops and the error is
// returned rather than being counted and looped past.
func (p *Pipeline) Run(ctx context.Context) (Stats, error) {
	var total, acked, failed int64
	start := time.Now()

	if p.cfg.KeyPlan == nil {
		p.warnf("no key configured, generating messages with a null key\n")
	}

loop:
	for {
		if p.cfg.Count > 0 && total >= int64(p.cfg.Count) {
			break
		}

		select {
		case <-ctx.Done():
			break loop
		default:
		}

		generated, err := p.cfg.Generator.Generate()
		if err != nil {
			return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, err
		}

		// The Key is planned after the Payload exists, because planting writes
		// into it. A key schema that cannot be honoured, or a path the Payload
		// does not carry, aborts the run before the record is counted: both are
		// true of every record, not just this one.
		var key any
		if p.cfg.KeyPlan != nil {
			key, err = p.cfg.KeyPlan.Apply(generated.Payload)
			if err != nil {
				return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, err
			}
		}
		total++

		keyBytes, data, err := p.cfg.Encoder.Encode(key, generated)
		if err != nil {
			failed++
			continue
		}

		if err := p.sink.Send(ctx, Outgoing{Key: keyBytes, Payload: data}); err != nil {
			failed++
			continue
		}

		acked++
		// Rate limiting stays an inline sleep. A sleeper seam is deliberately
		// deferred until a second consumer of pacing exists (ADR-0004); revisit
		// only when pacing tests demand it.
		time.Sleep(p.cfg.RateLimit)
	}

	return Stats{Total: total, Acked: acked, Failed: failed, Elapsed: time.Since(start)}, nil
}

func (p *Pipeline) warnf(format string, args ...any) {
	if p.cfg.Warn != nil {
		fmt.Fprintf(p.cfg.Warn, format, args...)
	}
}
